services:
  app:
    build: .
    env_file: .env
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis

  db:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: gadgetdb
    ports:
      - 5432:5432

  redis:
    image: redis
    ports:
      - 6379:6379
